### PR TITLE
example for deployment

### PR DESCRIPTION
**Pull request by jefking**

### CODE REVIEW

**Comment by itaysk** [comment]
Thanks @jefking for the contribution.
I have tried to deploy, but the structure created in wwwroot is from the root of the repo. we need to tell it to take only the function folder.
Regardless - Since it only deploys the function app, I'm not sure if the correct location for the file is the root of the repo. Either we link the logic app in, or move it into the functions folder.

**Comment by jefking** [comment]
we would just need to add a file like this: https://github.com/jefking/fn-webhook-queue/blob/master/.deployment
Which would look like this:
`[config]
project = function`

**Comment by jefking** [comment]
Added the deployment file; which will set the directory of the Azure Function to the functions directory.

**Comment by morsh** [comment]
Hi guys, I would love to see this deployment working as well. It makes a lot of sense to have a simple "Deploy to Azure" button rather than manually copying file.
The offered solution by @jefking looks good.

**Comment by itaysk** [comment]
The tribe has spoken... merged!

**Pull request merged**
